set nocompatible " be iMproved

call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-sensible'
Plug 'scrooloose/nerdtree'
Plug 'editorconfig/editorconfig-vim'
Plug 'kien/ctrlp.vim'
Plug 'terryma/vim-multiple-cursors'

Plug 'nono/vim-handlebars'
Plug 'othree/html5-syntax.vim'
Plug 'pangloss/vim-javascript'
Plug 'tpope/vim-markdown'

call plug#end()

"" display
set title
set number
set wrap
set scrolloff=3

"" search
set ignorecase
set smartcase
set hlsearch

"" no beep
"set visualbell
"set noerrorbells

set hidden " hide other files when opening one

" Spaces/Tabs
set expandtab "Use spaces instead of tabs
set shiftwidth=2
set tabstop=2

" highlight whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" learn vim, the right way
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>
imap <up> <nop>
imap <down> <nop>
imap <left> <nop>
imap <right> <nop>

" Bye Esc => ;;
:imap ;; <Esc>
:map ;; <Esc>

" No backup/swap files
set backupdir=
set directory=
set nowritebackup
set noswapfile

let mapleader = ","

" CtrlP
nmap <Leader>oo :CtrlP<cr>
nmap <Leader>of :CtrlPMixed<cr>
nmap <Leader>ob :CtrlPBuffer<cr>
nmap <Leader>or :CtrlPMRU<cr>
