" Vim configuration file
"
" Some good .vimrc
" - http://amix.dk/vim/vimrc.html
" - https://github.com/madx/propane/blob/master/vim/vimrc
" - https://github.com/necolas/dotfiles/blob/master/vim/vimrc
" - 

set nocompatible " be iMproved (you want vim, not just vi)

" ---

" Plugins

" use vim-plug to handle plugins

call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-sensible' " generic config that everyone (should) use
Plug 'scrooloose/nerdtree' " file tree
Plug 'editorconfig/editorconfig-vim' " .editorconfig file support (see editorconfig.org)
Plug 'kien/ctrlp.vim' " sublime text like ctrl+p (open file with fuzzy matching)
Plug 'terryma/vim-multiple-cursors' " multiple cursor, select some text then ctrl+n)
Plug 'nathanaelkane/vim-indent-guides' " indentation guides
Plug 'scrooloose/syntastic' " syntax error/linter

" More Syntax

Plug 'nono/vim-handlebars'
Plug 'othree/html5-syntax.vim'
Plug 'pangloss/vim-javascript'
Plug 'tpope/vim-markdown'

call plug#end()

"" No backup/swap files

set backupdir=
set directory=
set nowritebackup
set noswapfile

"" Display

set title

"" Line Number

set number
highlight LineNr cterm=none ctermfg=DarkGrey ctermbg=none

"" Don't wrap long line

set nowrap

"" Scolling will always some lines around cursor

set scrolloff=3

"" Search

set ignorecase
set smartcase " don't ignore case when a maj is used
set hlsearch " highlight search
" Clear the search highlight by pressing ENTER when in Normal mode (Typing commands)
:nnoremap <CR> :nohlsearch<CR>/<BS><CR>

"" No beep

set visualbell
set noerrorbells

"" Shared clipboard with the OS

set clipboard=unnamed

"" Spaces/Tabs

set expandtab "Use spaces instead of tabs
set shiftwidth=2
set tabstop=2

"" Indentation guides
set ts=2 sw=2
let g:indent_guides_start_level=2
let g:indent_guides_guide_size=1

" ---

" Remapping

"" learn vim, the right way

"map <up> <nop>
"map <down> <nop>
"map <left> <nop>
"map <right> <nop>
"imap <up> <nop>
"imap <down> <nop>
"imap <left> <nop>
"imap <right> <nop>
" this is preventing mouse scroll to affect vim

"" Bye Esc => jk or kj

map jk <Esc>
map kj <Esc>
imap jk <Esc>
imap kj <Esc>


"" Easier map leader

let mapleader = ","

" ---

" Visual stuff

set background=dark

"" highlight some specials chars

set listchars=eol:¬,tab:→→,extends:>,precedes:<
set list

"" highlight leading spaces

set conceallevel=2 concealcursor=nv
autocmd Syntax * syn match LeadingWhiteSpace /\(^\s*\)\@<=\s/ conceal cchar=·
  " example

"" adjust highlight color for conceal/special chars

highlight Conceal cterm=none ctermfg=DarkGrey ctermbg=none " leading whitespace
highlight SpecialKey cterm=none ctermfg=DarkGrey ctermbg=none " tab
highlight NonText cterm=none ctermfg=DarkGrey ctermbg=none " eol

" ---

" Plugins config

"" CtrlP

nmap <Leader>oo :CtrlP<cr>
nmap <Leader>of :CtrlPMixed<cr>
nmap <Leader>ob :CtrlPBuffer<cr>
nmap <Leader>or :CtrlPMRU<cr>

"" Syntastic

let g:syntastic_enable_signs = 1
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_error_symbol = "✗"
let g:syntastic_warning_symbol = "⚠"
let g:syntastic_check_on_open = 1
