#!/usr/bin/env zsh

DROPBOX_PATH=~/Sync/Dropbox # @todo found this from cli
GRABBOX_PATH=$DROPBOX_PATH/Apps/GrabBox

find $GRABBOX_PATH -mtime +$GRABBOX_CLEANUP_LIFETIME -type f -name "*.png" -delete

terminal-notifier \
  -title "GrabBox" \
  -message "Cleanup done" \
  -sound Pop \
  -contentImage /Applications/GrabBox.app/Contents/Resources/GrabBox.icns \
  -open file://$GRABBOX_PATH
