#!/usr/bin/env zsh

function group_lazy_load() {
  local script
  script=$1
  shift 1
  for cmd in "$@"; do
    alias $cmd="lazy_load \"$*\" $script $cmd"
    echo $cmd="lazy_load \"$*\" $script $cmd"
  done
}
