#!/usr/bin/env zsh

lazy_load() {
  # Act as a stub to another shell function/command. When first run, it will load the actual function/command then execute it.
  # E.g. This made my zsh load 0.8 seconds faster by loading `nvm` when "nvm", "npm" or "node" is used for the first time
  # $1: space separated list of alias to release after the first load
  # $2: file to source
  # $3: name of the command to run after it's loaded
  # $4+: argv to be passed to $3
  echo "Lazy loading $2 ..."

  # $1.split(' ') using the s flag. In bash, this can be simply ($1) #http://unix.stackexchange.com/questions/28854/list-elements-with-spaces-in-zsh
  # Single line won't work: local names=("${(@s: :)${1}}"). Due to http://stackoverflow.com/questions/14917501/local-arrays-in-zsh   (zsh 5.0.8 (x86_64-apple-darwin15.0))
  local -a names
  if [[ -n "$ZSH_VERSION" ]]; then
    names=("${(@s: :)${1}}")
  else
    names=($1)
  fi
  unalias "${names[@]}"
  source $2
  shift 2
  $*
}
