#!/usr/bin/env zsh

# `npmpublish` with an optional argument `patch`/`minor`/`major`/`<version>`
# defaults to `patch`
# require `npm i -g mversion`
function npmpublish() {
  git pull --rebase && \
  rm -rf node_modules && \
  npm install && \
  npm test && \

  mversion ${1:=patch} -m -n && \

  npm publish && \

  git push origin master && \
  git push origin master --tags

  npmrelease
}
