#!/usr/bin/env zsh

# `npmpublish` to safely tag, publish & release current repo version & state
function npmpublish() {
  trash node_modules &>/dev/null;
  git pull --rebase &&
  npm install &&
  npm test &&

  git tag $(node -e 'process.stdout.write(require("./package.json").version)') &&

  npm publish &&

  git push --follow-tags &&

  sleep 2 && # wait just a bit so GitHub detect the fresh tag

  # https://github.com/MoOx/setup/blob/master/bin/npmrelease
  npmrelease
}
