#!/usr/bin/env zsh

# `npmpublish` to safely tag, publish & release current repo version & state
function npmpublish() {
  git pull --rebase && \
  rm -rf node_modules && \
  npm install && \
  npm test && \

  git tag $(node -e 'process.stdout.write(require("./package.json").version)') && \

  npm publish && \

  git push origin master && \
  git push origin master --tags && \

  # https://github.com/MoOx/setup/blob/master/bin/npmrelease
  sleep 1 && npmrelease
}
