#!/bin/zsh

# define zsh as default shell
chsh -s /bin/zsh $USER

if ! type "git" > /dev/null; then
  if [[ "$(uname -s)" == "Darwin" ]]
  then
    # todo add an alternative to grab xcode from another computer accessible by local network
    xcode-select --install
    echo "Press return when XCode Developer Tools are installed"
    read -k
  fi
fi

if [[ ! -d $HOME/dotfiles ]]
then
  git clone http://github.com/MoOx/dotfiles.git $HOME/dotfiles
  git submodule init
else
  cd $HOME/dotfiles
  git pull
fi
git submodule update

. $HOME/dotfiles/bin/fireinthehole --full

echo_title "First run some applications"

# move that directly into each appropriated part
open "/Applications/Alfred 2.app"
open "/Applications/BitTorrent Sync.app"
open "/Applications/Cloud.app"
open "/Applications/Dash.app"
open "/Applications/Dropbox.app"
open "/Applications/Flux.app"
open "/Applications/Flycut.app"
open "/Applications/Shortcat.app"
open "/Applications/XtraFinder.app"
open "/Applications/Day-O.app"
open "$HOME/Applications/FirefoxNightly.app"
open "$HOME/Applications/Last.fm.app"
open "$HOME/Applications/LimeChat.app"
open "$HOME/Applications/Slate.app"
open "$HOME/Applications/Tunnelblick.app"

# todo add login items

if ! type "say" > /dev/null
then
  say "YO BITCH, setup is done \!"
  sleep 5
  say "HEY BITCH ! Did you heard what I just said \?"
fi
