#!/bin/zsh

if ! type "git" > /dev/null; then
    if [[ "$(uname -s)" == "Darwin" ]]
    then
        # todo add an alternative to grab xcode from another computer accessible by local network
        xcode-select --install
        echo "Press return when XCode Developer Tools are installed"
        read -k 
    fi
fi

if [[ ! -d $HOME/dotfiles ]]
    git clone http://github.com/MoOx/dotfiles.git $HOME/dotfiles
else
    cd $HOME/dotfiles
    git pull
fi

. $HOME/dotfiles/bin/fireinthehole
