#!/usr/bin/env zsh

## Sync
brewcaskinstall "syncthing-bar"
openifnot "syncthing-bar"
setupsh-recipe custom-folders

brewcaskinstall "Hyper"

# browser
brewcaskinstall "FirefoxNightly"
openifnot "FirefoxNightly"
setupsh-recipe firefox-user.js

setupsh-recipe ssh

## GPG
brewcaskinstall "/usr/local/bin/gpg" gpgtools
# contains gnupg gpg-agent pinentry + GPG keychain UI

## Zsh completion
brewinstall zsh-completions

# one keyboard/mouse for multiples machines
if ! ls /Applications/Synergy.app &> /dev/null
then
  open "http://synergy-project.org/"
  setupsh-accessibility-privacy-apps --insert synergy
fi

brewcaskinstall "Spectacle"

## Some utilities
brewcaskinstall "Flux"
openifnot "Flux"
brewcaskinstall "iStat Menus"
openifnot "iStat Menus"

## Development
setupsh-recipe git
brewcaskinstall "Atom"
brewcaskinstall "GitHub Desktop"

### Node
setupsh-recipe nvm
nvm install 8 # --reinstall-packages-from=node
nvm alias default 8
npm config set progress false
npm config set cache-min 20000 # 6 hours (60*60*6)
setupsh-recipe yarn
brewinstall watchman


# MAXIMUM SECURITY
brewcaskinstall "KeePassX"

if [ "$FIRSTRUN" = "true" ]; then macos-refresh; fi;

# safer than rm
npmig trash-cli

brewcaskinstall "Tunnelblick"
brewcaskinstall "WebTorrent"
brewcaskinstall "VLC"
brewcaskinstall "MPlayerX"

# apps
brewcaskinstall "Prefs Editor"
brewcaskinstall "AppCleaner"

##
# Stuff that are slow to download
# or that require human interaction
##
# dyndns
setupsh-recipe ddclient

# anti-thef
setupsh-recipe prey

##
# Less important stuff
#
# install later (not during the first run)
##
if [ "$FIRSTRUN" = "" ]
then
  # messaging
  brewcaskinstall "Gitter"
  brewcaskinstall "Discord"
  brewcaskinstall "Slack"
  brewcaskinstall "Skype"
  brewcaskinstall "Caprine" # Facebook Messenger
  brewcaskinstall "Telegram"

  # MORE BROWSER
  brewcaskinstall "Firefox"
  brewcaskinstall "Google Chrome"

  # YEAH I USE THAT
  brewcaskinstall "/Library/Java/JavaVirtualMachines" "java"
  brewcaskinstall "LibreOffice"

  # image
  brewcaskinstall "ImageOptim"

  # multimedia
  brewcaskinstall "Last.fm" "lastfm"
  brewcaskinstall "Jubler"

  # VIDEO GAMES \o/
  brewcaskinstall "Steam"

  # Because sometimes...
  brewcaskinstall "Transmission"
  brewcaskinstall "Cyberduck"

  # Data/Disk related
  brewcaskinstall "GrandPerspective"
  brewcaskinstall "SuperDuper!" "superduper"
fi

# for my mouse
brewcaskinstall "/Library/PreferencePanes/Logitech Control Center.prefPane" "logitech-control-center"
brewcaskinstall "Utilities/Logitech Unifying Software" "logitech-unifying"
