#!/usr/bin/env zsh

# one keyboard/mouse for multiples machines
brewcaskinstall "Synergy"

##
# Sync first
##
brewcaskinstall "BitTorrent Sync"
openifnot "BitTorrent Sync"
brewcaskinstall "Dropbox"
openifnot "Dropbox"

setupsh-recipe custom-folders

##
# Development
##

#brewcaskinstall "iTerm" "iterm2"
setupsh-recipe git
brewcaskinstall "GitHub"

### Node
setupsh-recipe node
# release tool
npmig mversion
# package helpers
npmig npm-check
npmig updatehammer

setupsh-recipe ssh
brewinstall zsh-completions

# window manager
brewcaskinstall Slate
openifnot "Slate"

# editor
brewcaskinstall atom

# browser
brewcaskinstall "FirefoxNightly" "firefox-nightly"
openifnot "FirefoxNightly"
setupsh-recipe firefox-user.js

# MAXIMUM SECURITY
brewcaskinstall "KeePassX"

# Some app from AppStore
openifnot "Tweetbot"

##
# Sharing
##
brewcaskinstall LimeChat
openifnot LimeChat
brewcaskinstall GrabBox
openifnot "GrabBox"
setupsh-recipe grabbox-cleanup
brewcaskinstall "CloudApp" cloud
#brewcaskinstall "Cloudup"

## Some utilities
brewcaskinstall "Flux"
openifnot "Flux"
brewcaskinstall "Day-O"
openifnot "Day-O"
brewcaskinstall "/opt/homebrew-cask/Caskroom/menumeters" "menumeters"
brewcaskinstall "Prefs Editor"
brewcaskinstall "AppCleaner"

# QuickLook plugins from https://github.com/sindresorhus/quick-look-plugins
brewcaskinstall "/opt/homebrew-cask/Caskroom/qlcolorcode" "qlcolorcode"
brewcaskinstall "/opt/homebrew-cask/Caskroom/qlstephen" "qlstephen"
brewcaskinstall "/opt/homebrew-cask/Caskroom/qlmarkdown" "qlmarkdown"
brewcaskinstall "/opt/homebrew-cask/Caskroom/quicklook-json" "quicklook-json"
brewcaskinstall "/opt/homebrew-cask/Caskroom/qlprettypatch" "qlprettypatch"
brewcaskinstall "/opt/homebrew-cask/Caskroom/quicklook-csv" "quicklook-csv"
brewcaskinstall "/opt/homebrew-cask/Caskroom/betterzipql" "betterzipql"
brewcaskinstall "/opt/homebrew-cask/Caskroom/webp-quicklook" "webp-quicklook"
brewcaskinstall "/opt/homebrew-cask/Caskroom/suspicious-package" "suspicious-package"

# reset QuickLook plugins
qlmanage -r &> /dev/null

if [ "$FIRSTRUN" = "true" ]; then osx-refresh; fi;

##
# Less important stuff
##

# safer than rm
npmig trash

# missing commands to OSX
brewinstall tree
brewinstall gpg

# better than man
npmig tldr

npmig travis-encrypt

# favicon
brewinstall icoutils

#sudo pip install --upgrade asciinema
#asciinema auth
#asciinema rec

# keybase.io
npmig keybase

brewcaskinstall "Transmission"

#brewcaskinstall Slack # don't work because -> "Slack 0.44.2.app"
brewcaskinstall "/opt/homebrew-cask/Caskroom/slack/" slack
brewcaskinstall Skype
brewcaskinstall Gitter

# multimedia
brewcaskinstall "VLC"
brewcaskinstall "MPlayerX"
brewcaskinstall "Last.fm" "lastfm"
openifnot "Last.fm.app"
#brewcaskinstall "Rdio"
brewcaskinstall "All2MP3"
brewcaskinstall "Subtitles"
brewcaskinstall "Jubler"
brewcaskinstall "Cyberduck"
brewcaskinstall "NameChanger"
brewcaskinstall "GrandPerspective"

# HD backup
brewcaskinstall "SuperDuper!" "superduper"

# VIDEO GAMES \o/
brewcaskinstall "Steam"

# MORE BROWSER
brewcaskinstall "phantomjs"
brewcaskinstall "Firefox"
brewcaskinstall "Google Chrome"
brewcaskinstall "Opera"
brewcaskinstall "/Library/Internet Plug-Ins/googletalkbrowserplugin.plugin" "google-hangouts"

##
# Stuff that are slow to download
# or that require human interaction
##
# dyndns
setupsh-recipe ddclient

# anti-thef
setupsh-recipe prey

# flash :(
brewcaskinstall "Utilities/Adobe Flash Player Install Manager" "flash"

# for my mouse
brewcaskinstall "/Library/PreferencePanes/Logitech Control Center.prefPane" "logitech-control-center"
brewcaskinstall "Utilities/Logitech Unifying Software" "logitech-unifying"

# YEAH I USE THAT
brewcaskinstall "/Library/Java/JavaVirtualMachines" "java"
brewcaskinstall "LibreOffice"

# no comment
brewcaskinstall "VirtualBox"

# not needed by default anymore
#setupsh-recipe dnsmasq
#setupsh-recipe apache
#setupsh-recipe php
#setupsh-recipe mysql

#brewtap caskroom/fonts
#brewcaskinstall "$HOME/Library/Fonts/Ubuntu-R.ttf" font-ubuntu
#brewcaskinstall "$HOME/Library/Fonts/Ubuntu Mono derivative Powerline.ttf" font-ubuntu-mono-powerline

# might be required http://software.intel.com/en-us/android/articles/intel-hardware-accelerated-execution-manager
# brewinstall android-sdk
#brewcaskinstall genymotion

# fix some menu bar icons for yosemite
#brew install imagemagick --with-libtiff
#ruby $SETUP_PATH/submodules/yosemite-menu-inverter/invert.rb

# Better perf for non Apple SSD
# at the end because need reboot
if [[ $COMPUTER_NAME == "iMoOx" ]]
then
  brewcaskinstall "Trim Enabler"
  openifnot "Trim Enabler"
fi
