#!/bin/zsh

brewinstall zsh-completions

# better than man
npmig tldr

# essential missing commands to OSX
brewinstall tree
brewinstall ssh-copy-id

# for icon fonts mainly
brewinstall fontforge
brewinstall ttfautohint

# to create favicons
brewinstall icoutils

brewtap tobli/browsertime
brewinstall sitespeedio/sitespeedio/sitespeed.io

#sudo pip install --upgrade asciinema
#asciinema auth
#asciinema rec
