#!/bin/zsh

TERM_PROFILE='FreshCut';
CURRENT_PROFILE="$(defaults read com.apple.terminal 'Default Window Settings')";
if [ "$CURRENT_PROFILE" != "$TERM_PROFILE" ]
then
  echo_title "Setup Terminal.app profile"
  open "$DOTFILES/components/_cli/$TERM_PROFILE.terminal"
  # Wait a bit to make sure the theme is loaded
  sleep 1

  defaults write com.apple.terminal 'Default Window Settings' -string "$TERM_PROFILE"
  defaults write com.apple.terminal 'Startup Window Settings' -string "$TERM_PROFILE"
fi
