#!/bin/zsh

brewcaskinstall "/Library/Java/JavaVirtualMachines" "java" 

brewcaskinstall "KeePassX" "keepassx"
brewcaskinstall "LibreOffice"

brewcaskinstall "Steam"
dockutil --add "/Applications/Steam.app" --after "Console"

#toadd
#openemu
#ntfs-free
#gfxcardstatus
#bootchamp
#SetAPPSync
