#!/bin/zsh

brewcaskinstall "/Library/Java/JavaVirtualMachines" "java"

brewcaskinstall "KeePassX"
brewcaskinstall "LibreOffice"

brewcaskinstall "Steam"
dockutil --add "/Applications/Steam.app"

#toadd
#openemu
#ntfs-free
#gfxcardstatus
#bootchamp
#SetAPPSync
