#!/bin/zsh

if ! type "node" > /dev/null
then
  echo_title_install "Node.js"
  brewinstall node
fi

echo_title_installupdate "NPM global packages"
if [ "$FULLFIRE" = "true" ]
then
  npmug
fi

# release tool
npmig mversion

# build tools
npmig component
npmig gulp
npmig grunt-cli

# browserify all the things
npmig browserify
npmig testling
npmig coverify
npmig tape

# code quality tools
npmig htmlhint
npmig csslint
npmig jshint
npmig jscs

# css tools
npmig autoprefixer

# happyplan launcher
npmig happyplan-cli

npmig travis-encrypt

# package helpers
npmig pkg-name
npmig bower
