#!/bin/zsh

if ! type node > /dev/null
then
  echo_title_install "Node.js"
  brewinstall node
fi

echo_title_installupdate "NPM global packages"
npmug

# release tool
npmig mversion

# package helpers
npmig npm-check
npmig updatehammer
