#!/bin/zsh

function full-setupsh() {
  echo "\n(╯°□°）╯ ︵ $CHAR_BOOM\n"

  # Ask for the administrator password upfront
  sudo -v

  # update from remote
  echo_title_update "from remote"

  git -C $SETUP_PATH pull origin master
  git -C $SETUP_PATH submodule init
  git -C $SETUP_PATH submodule update

  export FIRSTRUN=false
  if [ "$1" = "--firstrun" ]
  then
    export FIRSTRUN=true
  fi

  setupsh
}
