#!/usr/bin/env zsh

function setupsh-submodules-remove() {
  git -C $SETUP_PATH config -f .git/config --remove-section submodule.submodules/$1
  git -C $SETUP_PATH config -f .gitmodules --remove-section submodule.submodules/$1
  git -C $SETUP_PATH rm --cached submodules/$1
  git -C $SETUP_PATH commit -m "Remove submodule $1"
  rm -rf submodules/$1
  rm -rf $SETUP_PATH/.git/modules/submodules/$1
}
