#!/usr/bin/env zsh

function setupsh-run() {
  # Ask for the administrator password upfront
  sudo -v

  echo_title_installupdate ".dotfiles"
  dotfiles $SETUP_PATH/dotfiles

  # reload zshrc
  . $HOME/.zshrc

  setupsh-recipe brew
  brewinstall terminal-notifier

  echo_title_update "preferences"
  sourceFiles $SETUP_PATH/preferences/*.prefs

  if [ "$FIRSTRUN" = "true" ]
  then
    echo_title "Opening AppStore\nInstall your apps ;)"
    appstore
    echo_user "Hit enter when you are ready"
    read -e stuff
  fi

  notify "Password might be required"
  if [ "$FIRSTRUN" = "true" ]
  then
    sleep 5
    notify "Since it's a full run, it might be asked more than once. Check often until process is complete."
  fi

  source $SETUP_PATH/index

  osx-refresh

  notify "Setup complete ☑️"
}
