#!/usr/bin/env zsh

function setupsh-submodules-update() {
  git -C $SETUP_PATH submodule foreach git pull origin master
  git -C $SETUP_PATH add -A submodules
  git -C $SETUP_PATH commit -m "Update submodules"
}
