#!/usr/bin/env zsh

function setupsh-recipe () {
  SETUPSH_RECIPE_SETUP="$SETUP_PATH/recipes/$1.setup"
  if [[ -f "$SETUPSH_RECIPE_SETUP" ]]
  then
    source "$SETUPSH_RECIPE_SETUP"
  else
    echo "Fail to setup $1: no setup file in '$SETUPSH_RECIPE_SETUP'"
  fi
}
