#!/usr/bin/env zsh

function setupsh() {
  echo_title_installupdate ".dotfiles"
  dotfiles()

  # required first
  setupsh-recipe brew
  brewinstall terminal-notifier

  echo_title_update "preferences"
  sourceFiles $SETUP_PATH/preferences/*.prefs

  if [ "$FIRSTRUN" = "true" ]
  then
    echo_title "Opening AppStore\nInstall your apps ;)"
    appstore()
    echo_user "Hit enter when you are ready"
    read -e stuff
  fi

  notify "Password might be required"
  if [ "$FIRSTRUN" = "true" ]
  then
    sleep 5
    notify "Since it's a full run, it might be asked more than once. Check often until process is complete."
  fi

  # Ask for the administrator password upfront
  sudo -v

  source $SETUP_PATH/index

  osx-refresh

  echo ""
  notify "Setup complete ☑️"
}
