#!/bin/zsh
echo_title "Defining OS X options"

# Set wallpaper
#osascript -e "tell application \"System Events\" to set picture of every desktop to \"~/Dropbox/wallpapers/example.jpg\""

COMPUTER_NAME="$USER"
COMPUTER_MODEL=`sysctl -n hw.model`
if [[ $COMPUTER_MODEL == "iMac"* ]]
then
	COMPUTER_NAME="i$COMPUTER_NAME"
elif [[ $COMPUTER_MODEL == "MacBook"* ]]
then
	COMPUTER_NAME="Mac$COMPUTER_NAME"
fi
# notifying computer name update only if name will be changed
if [[ $COMPUTER_NAME != $(sudo scutil --get ComputerName) ]]
then
  echo_info "Computer name set to $COMPUTER_NAME"
fi
sudo scutil --set ComputerName $COMPUTER_NAME
sudo scutil --set HostName $COMPUTER_NAME
sudo scutil --set LocalHostName $COMPUTER_NAME
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string $COMPUTER_NAME

# Disable the sound effects on boot
sudo nvram SystemAudioVolume=" "

# Never go into computer sleep mode
systemsetup -setcomputersleep Off > /dev/null

# Enable subpixel font rendering on non-Apple LCDs
defaults write NSGlobalDomain AppleFontSmoothing -int 2

# recovery_message 'If this Mac is found, please call +33 6 78 13 54 39 - Si vous trouvez ce Mac, merci d\'appeler le 06 78 13 54 39': }
# https://github.com/boxen/puppet-osx/blob/master/manifests/recovery_message.pp

# Always show scrollbars
defaults write NSGlobalDomain AppleShowScrollBars -string "WhenScrolling"
# Possible values: `WhenScrolling`, `Automatic` and `Always`

# disable auto correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# expand save dialog
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

# expand print dialog
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true

# no .DS_Store on newtwork
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# disk utility debug menu
defaults write com.apple.DiskUtility DUDebugMenuEnabled -bool true

# Disable the “Are you sure you want to open this application?” dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Use scroll gesture with the Ctrl (^) key to zoom
defaults write com.apple.universalaccess HIDScrollZoomModifierMask 262144

# disable zoom with cmd+scroll
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool false

# Enable AirDrop over Ethernet and on unsupported Macs:
defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

# Save to disk (not to iCloud) by default
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# Set sidebar icon size to medium
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 2

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Enable spring loading for directories
defaults write NSGlobalDomain com.apple.springing.enabled -bool true

# Remove the spring loading delay for directories
defaults write NSGlobalDomain com.apple.springing.delay -float 0

# Disable Dashboard
defaults write com.apple.dashboard mcx-disabled -bool true

# Reset Launchpad, but keep the desktop wallpaper intact
find "$HOME/Library/Application Support/Dock" -name "*-*.db" -maxdepth 1 -delete

# Only use UTF-8 in Terminal.app
defaults write com.apple.terminal StringEncodings -array 4

# Don’t automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

# Reset Launchpad
find ~/Library/Application\ Support/Dock -name "*.db" -maxdepth 1 -delete

###
# iTerm 2
###

# Don’t display the annoying prompt when quitting iTerm
defaults write com.googlecode.iterm2 PromptOnQuit -bool false

###
# Time Machine
###

# Prevent Time Machine from prompting to use new hard drives as backup volume
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

# Disable local Time Machine backups
hash tmutil &> /dev/null && sudo tmutil disablelocal

source $DOTFILES/components/osx/preferences/ActivityMonitor
source $DOTFILES/components/osx/preferences/Dock
source $DOTFILES/components/osx/preferences/HotCorner
source $DOTFILES/components/osx/preferences/Keyboard
source $DOTFILES/components/osx/preferences/MenuBar
source $DOTFILES/components/osx/preferences/Mouse
source $DOTFILES/components/osx/preferences/Screencapture
source $DOTFILES/components/osx/preferences/Spotlight

source $DOTFILES/components/osx/preferences/apps/Finder.app
source $DOTFILES/components/osx/preferences/apps/Mail.app
source $DOTFILES/components/osx/preferences/apps/Safari.app

# Kill affected applications
fuckosx
for app in "Address Book" "Calendar" "Contacts" "Messages"
do
  killa "${app}"
done


# Enable local FTP Server
# used for some stuff (local wordpress) & wii ftp access
sudo launchctl load -w /System/Library/LaunchDaemons/ftp.plist > /dev/null 2>&1
