#!/bin/zsh

# `e` with no arguments opens the current directory in Sublime Text, otherwise
# opens the given location
function e() {
  if [ $# -eq 0 ]; then
    $EDITOR .
  else
    $EDITOR "$@"
  fi
}
