#!/bin/zsh

brewcaskinstall "Sublime Text" "sublime-text3"

if ! type "subl" > /dev/null; then
	echo_title "Configuring Sublime Text bin"
	ln -s /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/subl

	curl "https://sublime.wbond.net/Package%20Control.sublime-package" --out "$SUBLIME_TEXT_PREF_DIR/Installed Packages/Package Control.sublime-package"
	rm "$SUBLIME_TEXT_PREF_DIR/Packages/User/Package Control.sublime-settings"
	link_files "$DOTFILES/apps/sublime-text3/Package Control.sublime-settings" "$SUBLIME_TEXT_PREF_DIR/Packages/User/Package Control.sublime-settings"
	rm "$SUBLIME_TEXT_PREF_DIR/Packages/User/Preferences.sublime-settings"
	link_files "$DOTFILES/apps/sublime-text3/Preferences.sublime-settings" "$SUBLIME_TEXT_PREF_DIR/Packages/User/Preferences.sublime-settings"
fi
