#!/bin/zsh

# `np` with an optional argument `patch`/`minor`/`major`/`<version>`
# defaults to `patch`
function npmpublish() {
  git stash save beforenpmpublish 2> /dev/null
  git pull --rebase && \
  rm -rf node_modules && \
  npm install && \
  npm test && \
  npm version ${1:=patch} && \
  npm publish && \
  git push origin master && \
  git push origin master --tags
  git stash pop beforenpmpublish 2> /dev/null
}
