#!/bin/zsh

# `np` with an optional argument `patch`/`minor`/`major`/`<version>`
# defaults to `patch`
function npmpublish() {
  git pull --rebase && \
  npm install && \
  npm test && \
  npm version ${1:=patch} && \
  npm publish && \
  git push origin master && \
  git push origin master --tags
}
