#!/bin/zsh

# enhance OS X with some small utilities
brewcaskinstall "XtraFinder" "xtrafinder"
brewcaskinstall "AppCleaner" "appcleaner"
brewcaskinstall "Day-O" "day-o"
openifnot "Day-O" "/Applications/Day-O.app"

brewcaskinstall "Flux"
openifnot "Flux" "/Applications/Flux.app"

# I surprise myself never using this, maybe later
# brewcaskinstall "Shortcat" "shortcat"
# openifnot "Shortcat" "/Applications/Shortcat.app"

# New Spotlight kills Alfred :/
# brewcaskinstall "Alfred 2" "alfred"
# openifnot "Alfred 2" "/Applications/Alfred 2.app"
# # todo add to Alfred.app search scope
# # /Applications/Xcode.app/Contents/Applications/
# # /System/Library/CoreServices/
# # /System/Library/CoreServices/Applications/
# brew cask alfred link 2>&1 | grep -v "Alfred is already linked to homebrew-cask."

# required by I don't know why
brewcaskinstall "Utilities/XQuartz" "xquartz"

# Trim enable for non Apple SSD
brewcaskinstall "Trim Enabler"

brewcaskinstall "/opt/homebrew-cask/Caskroom/menumeters" "menumeters"
# append menumeter & do not touch other menu extras
defaults write com.apple.systemuiserver menuExtras -array-add \
  "/opt/homebrew-cask/Caskroom/menumeters/latest/MenuMeters Installer.app/Contents/Resources/MenuMeters.prefPane/Contents/Resources/MenuMeterMem.menu" \
  "/opt/homebrew-cask/Caskroom/menumeters/latest/MenuMeters Installer.app/Contents/Resources/MenuMeters.prefPane/Contents/Resources/MenuMeterCPU.menu" \
  "/opt/homebrew-cask/Caskroom/menumeters/latest/MenuMeters Installer.app/Contents/Resources/MenuMeters.prefPane/Contents/Resources/MenuCracker.menu"
fuckosxmenubar

# QuickLook plugins from https://github.com/sindresorhus/quick-look-plugins
brewcaskinstall "/opt/homebrew-cask/Caskroom/qlcolorcode" "qlcolorcode"
brewcaskinstall "/opt/homebrew-cask/Caskroom/qlstephen" "qlstephen"
brewcaskinstall "/opt/homebrew-cask/Caskroom/qlmarkdown" "qlmarkdown"
brewcaskinstall "/opt/homebrew-cask/Caskroom/quicklook-json" "quicklook-json"
brewcaskinstall "/opt/homebrew-cask/Caskroom/qlprettypatch" "qlprettypatch"
brewcaskinstall "/opt/homebrew-cask/Caskroom/quicklook-csv" "quicklook-csv"
brewcaskinstall "/opt/homebrew-cask/Caskroom/betterzipql" "betterzipql"
brewcaskinstall "/opt/homebrew-cask/Caskroom/webp-quicklook" "webp-quicklook"
brewcaskinstall "/opt/homebrew-cask/Caskroom/suspicious-package" "suspicious-package"

# reset QuickLook plugins
qlmanage -r &> /dev/null
