#!/bin/zsh

# from AppStore
#dockutil --no-restart --add "/Applications/Wunderlist.app" --after "Calendar"

# from AppStore
dockutil --no-restart --add "/Applications/Tweetbot.app" --before "Messages"
openifnot "Tweetbot" "/Applications/Tweetbot.app"

# from AppStore
# todo get this app not from appstore
# https://github.com/TermiT/Flycut/issues/56
openifnot "Flycut" "/Applications/Flycut.app"
plistbuddy "Application Support/Flycut/com.generalarcade.flycut" "Set stickyBezel 1"
plistbuddy "Application Support/Flycut/com.generalarcade.flycut" "Set displayNum 40"
plistbuddy "Application Support/Flycut/com.generalarcade.flycut" "Set rememberNum 99"
plistbuddy "Application Support/Flycut/com.generalarcade.flycut" "Set menuIcon 1"
plistbuddy "Application Support/Flycut/com.generalarcade.flycut" "Set loadOnStartup 1"
plistbuddy "Application Support/Flycut/com.generalarcade.flycut" "Set removeDuplicates 1"


brewcaskinstall "Prefs Editor"

# enhance OS X with some small utilities
brewcaskinstall "XtraFinder"
openifnot "XtraFinder" "/Applications/XtraFinder.app"

brewcaskinstall "AppCleaner"

brewcaskinstall "Day-O" "day-o"
openifnot "Day-O" "/Applications/Day-O.app"

brewcaskinstall "Flux"
openifnot "Flux" "/Applications/Flux.app"

# I surprise myself never using this, maybe later
# brewcaskinstall "Shortcat" "shortcat"
# openifnot "Shortcat" "/Applications/Shortcat.app"

# New Spotlight kills Alfred :/
# brewcaskinstall "Alfred 2" "alfred"
# openifnot "Alfred 2" "/Applications/Alfred 2.app"
# # todo add to Alfred.app search scope
# # /Applications/Xcode.app/Contents/Applications/
# # /System/Library/CoreServices/
# # /System/Library/CoreServices/Applications/
# brew cask alfred link 2>&1 | grep -v "Alfred is already linked to homebrew-cask."

# required by I don't know why
brewcaskinstall "Utilities/XQuartz" "xquartz"

# Trim enable for non Apple SSD
brewcaskinstall "Trim Enabler"

brewcaskinstall "/opt/homebrew-cask/Caskroom/menumeters" "menumeters"
# append menumeter & do not touch other menu extras
defaults write com.apple.systemuiserver menuExtras -array-add \
  "/opt/homebrew-cask/Caskroom/menumeters/latest/MenuMeters Installer.app/Contents/Resources/MenuMeters.prefPane/Contents/Resources/MenuMeterMem.menu" \
  "/opt/homebrew-cask/Caskroom/menumeters/latest/MenuMeters Installer.app/Contents/Resources/MenuMeters.prefPane/Contents/Resources/MenuMeterCPU.menu" \
  "/opt/homebrew-cask/Caskroom/menumeters/latest/MenuMeters Installer.app/Contents/Resources/MenuMeters.prefPane/Contents/Resources/MenuCracker.menu"
defaults write com.ragingmenace.MenuMeters CPUAverageMultiProcs 1
defaults write com.ragingmenace.MenuMeters CPUDisplayMode 2
defaults write com.ragingmenace.MenuMeters CPUGraphLength 20
defaults write com.ragingmenace.MenuMeters CPUInterval 1
defaults write com.ragingmenace.MenuMeters CPUSystemColor   -string "<040b7374 7265616d 74797065 6481e803 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016301 84046666 66660000 000186>"
defaults write com.ragingmenace.MenuMeters CPUUserColor     -string "<040b7374 7265616d 74797065 6481e803 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016301 84046666 66668395 5edf3e83 9a1bed3e 8382d0fc 3e0186>"
defaults write com.ragingmenace.MenuMeters MemDisplayMode 1
defaults write com.ragingmenace.MenuMeters MemInterval 10
defaults write com.ragingmenace.MenuMeters MemFreeColor     -string "<040b7374 7265616d 74797065 6481e803 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016302 84046666 66660083 0000003f 000186>"
defaults write com.ragingmenace.MenuMeters MemUsedColor     -string "<040b7374 7265616d 74797065 6481e803 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016302 84046666 66668300 00003f00 000186>"
defaults write com.ragingmenace.MenuMeters MemInactiveColor -string "<040b7374 7265616d 74797065 6481e803 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016306 84034040 40848484 084e5353 7472696e 67019484 012b0653 79737465 6d868496 98096772 6964436f 6c6f7286 84939503 84026666 83000000 3f018686>"
defaults write com.ragingmenace.MenuMeters MemWireColor     -string "<040b7374 7265616d 74797065 6481e803 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016306 84034040 40848484 084e5353 7472696e 67019484 012b0653 79737465 6d868496 98186469 7361626c 6564436f 6e74726f 6c546578 74436f6c 6f728684 93950384 02666683 abaaaa3e 018686>"
fuckosxmenubar

# QuickLook plugins from https://github.com/sindresorhus/quick-look-plugins
brewcaskinstall "/opt/homebrew-cask/Caskroom/qlcolorcode" "qlcolorcode"
brewcaskinstall "/opt/homebrew-cask/Caskroom/qlstephen" "qlstephen"
brewcaskinstall "/opt/homebrew-cask/Caskroom/qlmarkdown" "qlmarkdown"
brewcaskinstall "/opt/homebrew-cask/Caskroom/quicklook-json" "quicklook-json"
brewcaskinstall "/opt/homebrew-cask/Caskroom/qlprettypatch" "qlprettypatch"
brewcaskinstall "/opt/homebrew-cask/Caskroom/quicklook-csv" "quicklook-csv"
brewcaskinstall "/opt/homebrew-cask/Caskroom/betterzipql" "betterzipql"
brewcaskinstall "/opt/homebrew-cask/Caskroom/webp-quicklook" "webp-quicklook"
brewcaskinstall "/opt/homebrew-cask/Caskroom/suspicious-package" "suspicious-package"

# reset QuickLook plugins
qlmanage -r &> /dev/null
