#!/bin/zsh

if ! type "apm" > /dev/null
then
  brewcaskinstall atom
fi

atomicon

dockutil --add "/Applications/Atom.app" --before "Console"

fuckosxprefs
fuckosxdock

if type "apm" > /dev/null
then
  apminstall auto-update-packages

  # theme
  apminstall yosemite-unity-ui
  apminstall file-type-icons

  # editor enhancements
  apminstall recent-projects
  apminstall show-in-folder
  apminstall zen
  apminstall open-in-github-app
  apminstall gist-it
  apminstall tabs-to-spaces
  apminstall autocomplete-plus
  #apminstall sublime-tabs

  # git
  apminstall merge-conflicts
  apminstall git-blame

  # code quality
  apminstall editorconfig
  apminstall linter # for linter-*
  apminstall docblockr
  apminstall travis-ci-status

  # health
  apminstall break

  # editor ui
  apminstall swap-panes
  apminstall move-panes
  apminstall resize-panes
  apminstall maximize-panes

  # html/css/js
  apminstall atom-beautify

  # html
  apminstall close-tags
  apminstall htmlhint

  # css
  apminstall linter-csslint
  apminstall atom-color-highlight
  apminstall color-picker
  apminstall bezier-curve-editor

  # js
  apminstall linter-jscs
  apminstall linter-jshint
  apminstall linter-jsonlint
  apminstall language-jade
  apminstall mocha-test-runner

    # nodejs
    apminstall npm-install
    apminstall npm-docs

    # jsx
    apminstall language-jsx
    apminstall linter-jsxhint

  # NO COMMENT
  apminstall language-apache
fi
