#!/bin/zsh

if ! type "apm" > /dev/null
then
  brewcaskinstall atom
fi

# Atom Yosemite Icon https://dribbble.com/shots/1590423-Atom-Yosemite-Icon
setfileicon "$DOTFILES/components/atom/atom-yosemite.icns" "/Applications/Atom.app"

dockutil --add "/Applications/Atom.app" --before "Console"

if type "apm" > /dev/null
then
  apminstall auto-update-packages

  # theme
  # apminstall monokai-tweaked-ui
  # apminstall monokai-tweaked-syntax
  # apminstall unity-ui
  # apminstall unity-dark-ui
  apminstall yosemite-unity-ui
  apminstall file-type-icons

  # editor enhancements
  apminstall zen
  apminstall show-in-folder
  apminstall open-in-github-app
  apminstall gist-it
  apminstall tabs-to-spaces
  apminstall autocomplete-plus
  apminstall sublime-tabs

  apminstall merge-conflicts
  apminstall git-blame

  apminstall editorconfig
  apminstall linter # for linter-*

  apminstall docblockr
  apminstall travis-ci-status

  # editor ui
  apminstall swap-panes
  apminstall move-panes
  apminstall resize-panes
  apminstall maximize-panes

  # html/css/js
  apminstall atom-beautify

  # html
  apminstall close-tags
  apminstall htmlhint

  # css
  apminstall linter-csslint
  apminstall atom-color-highlight
  apminstall color-picker
  apminstall bezier-curve-editor

  # js
  apminstall linter-jscs
  apminstall linter-jshint
  apminstall linter-jsonlint
  apminstall language-jade

    # nodejs
    apminstall npm-install
    apminstall npm-docs

    # jsx
    apminstall language-jsx
    apminstall linter-jsxhint

  # NO COMMENT
  apminstall language-apache
fi
