#!/bin/zsh

brewcaskinstall "LimeChat" $HOME/Applications
dockutil --no-restart --add "~/Applications/LimeChat.app" --after "Messages"
openifnot "LimeChat" "$HOME/Applications/LimeChat.app"

LIMECHAT_THEME="$LIMECHAT_THEMES/LimeChat-theme-Monokai-Soda"
if [ ! -e "$LIMECHAT_THEME.css" ]
then
  echo_title_install "LimeChat theme"
  git clone https://github.com/MoOx/LimeChat-theme-Monokai-Soda.git $LIMECHAT_THEME
  ln -s $LIMECHAT_THEME/LimeChat-theme-Monokai-Soda.* $LIMECHAT_THEME
else
  echo_title_update "LimeChat theme"
  git -C $LIMECHAT_THEME pull
fi

brewcaskinstall "Skype"
dockutil --no-restart --add "/Applications/Skype.app" --after "LimeChat"

brewcaskinstall "Slack"
dockutil --no-restart --add "/Applications/Slack.app" --after "LimeChat"

fuckosxdock
