#!/bin/zsh

# for vpn
brewcaskinstall "Tunnelblick" $HOME/Applications

# just in case
brewcaskinstall "ImageOptim" $HOME/Applications
brewcaskinstall "ImageAlpha" $HOME/Applications

# more utilities
brewcaskinstall "Mou" $HOME/Applications

brewcaskinstall "Synergy" $HOME/Applications

brewcaskinstall "NameChanger" $HOME/Applications

brewcaskinstall "GrandPerspective" $HOME/Applications

brewcaskinstall "VirtualBox" $HOME/Applications
brewcaskinstall "VMWare Fusion" $HOME/Applications

fuckosxdock
