#!/bin/zsh

brewinstall zsh-completions
brewinstall terminal-notifier

#brewcaskinstall "iTerm" "iterm2" $HOME/Applications

source $DOTFILES/components/_cli/preferences/Terminal
#source $DOTFILES/components/_cli/preferences/iTerm2

# safer than rm
npmig trash
