#!/bin/zsh

brewinstall zsh-completions
brewinstall terminal-notifier

#dockutil --no-restart --add "$HOME/Applications/Utilities/Terminal.app" --before "Console"
#brewcaskinstall "iTerm" "iterm2" $HOME/Applications
#dockutil --no-restart --add "$HOME/Applications/iTerm.app" --before "Console"

source $DOTFILES/components/_cli/preferences/Terminal
source $DOTFILES/components/_cli/preferences/iTerm2

# better than man
npmig tldr

# safer than rm
npmig trash

# essential missing commands to OSX
brewinstall tree
brewinstall ssh-copy-id

# misc
npmig travis-encrypt
brewinstall icoutils

#sudo pip install --upgrade asciinema
#asciinema auth
#asciinema rec

brewinstall gpg
npmig keybase # keybase.io
