#!/bin/zsh

brewinstall zsh-completions

# better than man
npmig tldr

# safer than rm
npmig trash

# essential missing commands to OSX
brewinstall tree
brewinstall ssh-copy-id

# to create favicons
brewinstall icoutils

brewtap sitespeedio/sitespeedio
brewtap tobli/browsertime
brewinstall sitespeed.io

#sudo pip install --upgrade asciinema
#asciinema auth
#asciinema rec
