#!/bin/zsh

brewcaskinstall "KeePassX" "keepassx2"
brewcaskinstall "LibreOffice"
brewcaskinstall "Steam"
dockutil --add "~/Applications/Steam.app" --after "Console"

#toadd
#openemu
#ntfs-free
#gfxcardstatus
#bootchamp
#SetAPPSync
