#!/bin/zsh

if ! type "ddclient" > /dev/null
then
  echo_title "Installing a Dynamic DNS client"
  brewinstall ddclient

  # ddclient human configuration & auto start
  if ! ls /Library/LaunchDaemons/homebrew.mxcl.ddclient.plist > /dev/null
  then
    sudo cp ddclient.conf /usr/local/etc/ddclient
    $EDITOR_SYNC /usr/local/etc/ddclient/ddclient.conf

    sudo brew services start ddclient
    # brew usually use ln -sfv for plist, so just in case the line
    # above is not working next time I setup a machine, I'll keep the 2 lines below
    # sudo cp -fv /usr/local/opt/ddclient/*.plist /Library/LaunchDaemons
    # sudo launchctl load /Library/LaunchDaemons/homebrew.mxcl.ddclient.plist
  fi
fi
