#!/bin/zsh

##
# Synced folder
##
brewcaskinstall "BitTorrent Sync"
openifnot "BitTorrent Sync" "/Applications/BitTorrent Sync.app"
brewcaskinstall "Dropbox"
openifnot "Dropbox" "/Applications/Dropbox.app"

sudo rm -rf $HOME/Library/Fonts; ln -s $DIR_SYNC_BTSYNC/Fonts $HOME/Library/Fonts

sudo rm -rf $HOME/Music; ln -s $DIR_SYNC/Music $HOME/Music
sudo rm -rf $HOME/iTunes; ln -s $HOME/Music $HOME/iTunes
sudo rm -rf $HOME/Pictures; ln -s $DIR_SYNC/Pictures $HOME/Pictures

# Customize some icon (setfileicon is a custom command from my Dev*/bin)
setfileicon $OS_ICONS_DIR/GroupFolder.icns $DIR_SYNC
setfileicon $OS_ICONS_DIR/UsersFolderIcon.icns $DIR_SYNC/BTSync
setfileicon $OS_ICONS_DIR/LibraryFolderIcon.icns $DIR_SYNC/BTSync/Library
setfileicon $OS_ICONS_DIR/DeveloperFolderIcon.icns $DIR_SYNC/Development
setfileicon $OS_ICONS_DIR/PicturesFolderIcon.icns $DIR_SYNC/Pictures
#setfileicon $OS_ICONS_DIR/MovieFolderIcon.icns $HOME/Movies
setfileicon $OS_ICONS_DIR/MusicFolderIcon.icns $HOME/Music

###
# Cloud.app
###
brewcaskinstall "Cloud" "cloudapp" $HOME/Applications
openifnot "Cloud" "$HOME/Applications/Cloud.app"

###
# Transmission.app
###
brewcaskinstall "Transmission"

defaults write org.m0k.transmission UseIncompleteDownloadFolder -bool true
defaults write org.m0k.transmission IncompleteDownloadFolder -string "${HOME}/Downloads/Torrents"
defaults write org.m0k.transmission DownloadAsk -bool false
defaults write org.m0k.transmission DeleteOriginalTorrent -bool true

# because of my shitty 2Mb connection
defaults write org.m0k.transmission QueueDownloadNumber 2
defaults write org.m0k.transmission DownloadLimit 150
defaults write org.m0k.transmission SpeedLimitDownloadLimit 50
defaults write org.m0k.transmission SpeedLimitUploadLimit 5
defaults write org.m0k.transmission UploadLimit 5

defaults write org.m0k.transmission WarningDuplicate -bool false
defaults write org.m0k.transmission WarningDonate -bool false
defaults write org.m0k.transmission WarningLegal -bool false

##
# Misc
##
brewcaskinstall "Cyberduck"
brewcaskinstall "SuperDuper!" "superduper"
