#!/bin/zsh

# Apache configuration
if ! cat $APACHE_CONF | grep $APACHE_CONF_DEV_PATH > /dev/null
then
  if ls $APACHE_CONF_DEV_PATH &> /dev/null
  then
    echo_title "Configuring OS X Apache"
    echo "\nInclude $APACHE_CONF_DEV_PATH/*.conf" | sudo tee -a $APACHE_CONF
    apacheconfigtest
    apacherestart
  fi
fi

# PHP

if ! ls $(brew --prefix)/bin/php &> /dev/null
then
  echo_title_install "PHP"
  brewtap homebrew/homebrew-php
  brewinstall php55
  #brewinstall php55-http
fi

# MySQL
if ! type "mysql" > /dev/null
then
  echo_title_install "MySQL"
  brewinstall mysql
  ln -sfv /usr/local/opt/mysql/*.plist ~/Library/LaunchAgents
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist
fi
