#!/bin/zsh

if ! type "apm" > /dev/null
then
  brewcaskinstall atom
fi

dockutil --add "/Applications/Atom.app" --before "Console"

if type "apm" > /dev/null
then
  apminstall auto-update-packages

  # theme
  apminstall monokai-tweaked-ui
  apminstall monokai-tweaked-syntax

  # editor enhancements
  apminstall show-in-folder
  apminstall open-in-github-app
  apminstall gist-it
  apminstall tabs-to-spaces
  apminstall autocomplete-plus

  apminstall atom-prettify
  apminstall merge-conflicts

  apminstall editorconfig
  apminstall linter

  apminstall docblockr
  apminstall travis-ci-status

  # html
  apminstall close-tags
  apminstall htmlhint

  # css
  apminstall csslint
  apminstall css-color-highlighting

  # js
  apminstall linter-jscs
  apminstall linter-jshint
  apminstall linter-json
  apminstall language-jade

  # nodejs
  apminstall npm-install
  apminstall npm-docs

  #jsx
  apminstall language-jsx
  apminstall linter-jsxhint

  apminstall language-apache
fi
