#!/bin/zsh

if ! type "apm" > /dev/null
then
	apm install editorconfig
	apm install docblockr
	apm install close-tags
	apm install htmlhint
	apm install csslint
	apm install linter
	apm install linter-jscs
	apm install linter-jshint
	apm install css-color-highlighting
	apm install rdio
	apm install atom-prettify
	apm install npm-install
	apm install npm-docs
	apm install show-in-folder
	apm install open-in-github-app
	apm install gist-it
	apm install travis-ci-status
	apm install autocomplete-plus
	apm install tabs-to-spaces
	apm install language-apache
	apm install merge-conflicts
	apm install auto-update-packages

else
	echo "Atom needs to be installed by hand (private beta). Please visit atom.io,\nthen use this setup again"
fi
