#!/usr/bin/env zsh

export SETUP_PATH=$HOME/setup
export PATH=$SETUP_PATH/setupsh/bin:$PATH
export PATH=$SETUP_PATH/recipes:$PATH

# load colors
autoload colors && colors
for COLOR in RED GREEN YELLOW BLUE MAGENTA CYAN BLACK WHITE; do
    # todo wrap colours between %{ %} to avoid weird gaps in autocomplete
    eval COLOR_$COLOR='$fg_no_bold[${(L)COLOR}]'
    eval COLOR_$COLOR_BOLD='$fg_bold[${(L)COLOR}]'
done
eval COLOR_RESET='$reset_color'

# add some helpers for display
export CHAR_OK=✔
export CHAR_ERROR=✗
export CHAR_BOOM=💥
export CHAR_STARTER=❯

function echo_info () { echo "${COLOR_BLUE}i${COLOR_RESET} $1" }
function echo_user () { echo "${COLOR_YELLOW}?${COLOR_RESET} $1" }
function echo_success () { echo "${COLOR_GREEN}${CHAR_OK}${COLOR_RESET} $1" }
function echo_fail () { echo "${COLOR_RED}${CHAR_ERROR}${COLOR_RESET} $1\n"; exit }
function echo_title () { echo "${COLOR_CYAN}${CHAR_STARTER} $@${COLOR_RESET}" }
function echo_title_install () { echo_title "Installing" $1 "..." }
function echo_title_update () { echo_title "Updating" $1 "..." }
function echo_title_installupdate () { echo_title "Installing/Updating" $1 "..." }

# stupid var to avoid Darwin test all the time
# not sure it's better
export OS=unix
if [[ $(uname) = "Darwin" ]]; then; export OS=osx; fi
#if [[ $OS == "osx" ]]; then; echo "yeahyyyy"; fi

# load setupsh core functions
for file in $SETUP_PATH/setupsh/functions/*
do
  # echo "Sourcing $file"
  source $file
done

##
# Source recipes
##
typeset -U config_files

# load the path files
sourceFiles $SETUP_PATH/recipes/*.path

# load everything but the path and completion files
sourceFiles $SETUP_PATH/recipes/*.source
sourceFiles $SETUP_PATH/recipes/*.aliases

# initialize autocomplete here, otherwise functions won't be loaded
autoload -U compinit
compinit
# load every completion after autocomplete loads
sourceFiles $SETUP_PATH/recipes/*.completion

loadFunctionsFromPath $SETUP_PATH/setupsh/functions
loadFunctionsFromPath $SETUP_PATH/functions
