#!/usr/bin/env zsh

export SETUP_PATH=$HOME/setup
export PATH=$SETUP_PATH/bin:$PATH
export PATH=$SETUP_PATH/setupsh/bin:$PATH
export PATH=$SETUP_PATH/setupsh/recipes:$PATH

# load colors
autoload colors && colors
for COLOR in RED GREEN YELLOW BLUE MAGENTA CYAN BLACK WHITE; do
  # todo wrap colours between %{ %} to avoid weird gaps in autocomplete
  eval export COLOR_$COLOR='$fg_no_bold[${(L)COLOR}]'
  eval export COLOR_$COLOR_BOLD='$fg_bold[${(L)COLOR}]'
done
eval export COLOR_RESET='$reset_color'

# add some helpers for display
export CHAR_OK=✔
export CHAR_ERROR=✗
export CHAR_BOOM=💥
export CHAR_STARTER=❯

# stupid var to avoid Darwin test all the time
# not sure it's better
export OS=unix
if [[ $(uname) = "Darwin" ]]; then; export OS=macOS; fi
#if [[ $OS == "macOS" ]]; then; echo "yeahyyyy"; fi

# load setupsh core functions
for file in $SETUP_PATH/setupsh/functions/*
do
  # echo "Sourcing $file"
  source $file
done

##
# Source recipes
##
typeset -U config_files

# load the path files
# sourceFiles $SETUP_PATH/setupsh/recipes/*.path

# load everything but the path and completion files
# sourceFiles $SETUP_PATH/setupsh/recipes/*.source

# initialize autocomplete here, otherwise functions won't be loaded
autoload -U compinit
compinit
# load every completion after autocomplete loads
sourceFiles $SETUP_PATH/setupsh/recipes/*.completion

loadFunctionsFromPath $SETUP_PATH/setupsh/functions
loadFunctionsFromPath $SETUP_PATH/functions
