#!/bin/zsh

if ! type "brew" > /dev/null
then
  echo_title_install "Homebrew (brew)"
  ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go/install)"
  brew doctor
else
  echo_title_update "Homebrew (brew)"
  brewu
  brew cleanup
fi

brewtap homebrew/dupes
brewtap homebrew/versions

# cask
brewtap caskroom/cask
brewtap caskroom/versions
brewinstall "brew-cask"
